---
- name: update rhel password
  hosts: update_servers
  become: true

  vars:
    update_username: "testroot1"
    update_password: "password1"

  tasks:
    
    # Print User Pass and its updates
    - name: Print User Pass and updated user pass
      ansible.builtin.debug:
        msg: 
          - "update_username {{ update_username }}"
          - "update_password {{ update_password }}"
    
    # update user password
    # Content suggestion provided by Ansible Lightspeed
    - name: Update user password
      ansible.builtin.user:
        name: "{{ update_username }}"
        password: "{{ update_password | password_hash('sha512')  }}"
      no_log: True